CSCI-GA-2820-SP24-003/shopcarts

- service/models.py
- service/models/__init__.py
- service/models/persistent_base.py
- service/models/shop_cart.py
- service/models/shop_cart_item.py
- service/routes.py
- tests/factories.py
- tests/test_models.py
- tests/test_routes.py
- tests/test_shop_cart.py
- tests/test_shop_cart_item.py
- Shop Cart Model added
- 100% test coverage
Schema attributes:
- id
- user_id
- name
- total_price
- status
> Add database model

- service/routes.py
- tests/test_routes.py
- List shopcarts endpoint added on /shopcarts
- Added test - not testable - dependency on create shopcart endpoint
> List shopcarts

- service/__init__.py
- service/models/__init__.py
- service/models/shop_cart.py
- service/routes.py
- tests/factories.py
- tests/test_routes.py
- tests/test_shop_cart.py
- tests/test_shop_cart_item.py
Reverts CSCI-GA-2820-SP24-003/shopcarts#22
> Revert "Create shopcart"

- service/routes.py
- tests/test_routes.py
- tests/test_shop_cart.py
- tests/test_shop_cart_item.py
Made the following changes
- Added update shopcart endpoint in routes.py
- Added test cases for update shopcart endpoint
> Added Update Shopcart endpoint

- service/routes.py
- tests/test_routes.py
Made the following changes:
-Added delete shopcart endpoint in 'routes.py'
-Added test case for delete shopcart endpoint
> Added delete shopcart endpoint

- service/models/shop_cart.py
- service/models/shop_cart_item.py
- service/routes.py
- tests/factories.py
- tests/test_routes.py
- tests/test_shop_cart.py
- tests/test_shop_cart_item.py
add shopcart item read function 
add read shopcart function because the current implementation needs this function 
add more testcases in test_shop_cart.py
> Read shopcart item

- service/routes.py
- tests/test_routes.py
- tests/test_shop_cart_item.py
Made the following changes:
-Added update shopcart item endpoint in 'routes.py'
-Added test case for update shopcart item
> Added update shopcart item endpoint

- service/models/shop_cart_item.py
- service/routes.py
- tests/test_routes.py
- tests/test_shop_cart.py
- tests/test_shop_cart_item.py
Made the following changes 
-Added list-shop-cart-item endpoint in 'routes.py'
-Added test cases
> added list-shop_cart_item

- service/models/shop_cart_item.py
- tests/test_routes.py
- tests/test_shop_cart.py
- tests/test_shop_cart_item.py
add more test cases to make sure the coverage reach beyond 95%
> Add testcases

- service/routes.py
Create shopcart item wasn't returning the location url
> Create Shopcart Item - Bug Fix

- service/models/shop_cart_item.py
- service/routes.py
- tests/test_routes.py
update the quantity of an item in the shopart:
when adding the item with the same name, update the overall quantity of the item by the quantity of the new item
> Update item quantity

- service/models/shop_cart.py
- service/routes.py
- tests/test_routes.py
- tests/test_shop_cart.py
Made the following changes
- Added search shopcart by user_id endpoint in routes.py
- Added test cases for search shopcart by user_id
- Added find by user_id method
> Added Search Shopcart by User_id

- service/models/shop_cart.py
- tests/factories.py
- tests/test_routes.py
- tests/test_shop_cart.py
Made the following changes:
-Added status to the shopcart
> added status to shopcart

- service/models/shop_cart.py
- service/routes.py
- tests/test_routes.py
Made the Following Changes:
-Added find by status method
-Added sort shopcart by shopcart status endpoint
-Added test cases
> Added Sort_Shopcart_by_ShopcartStatus

- features/shopcart.feature
- service/static/index.html
- service/static/js/rest_api.js
Create shopcart button implemented UI + tests
> Create button UI + tests

- features/shopcart.feature
- features/steps/shopcarts_steps.py
- features/steps/web_steps.py
- service/static/index.html
- service/static/js/rest_api.js
add delete shopcart related feature file, index.html file and rest_api.js file 
add list shopcart related feature file, index.html file and rest_api.js file
> Delete shopcart feature and list shopcart feature

- features/shopcart.feature
- service/static/js/rest_api.js
Made the following changes:
-added update shopcart related feature file and rest_api.js file
-added read shopcart related feature file and rest_api.js file
> Added update shopcart feature

- features/shopcart.feature
- service/static/js/rest_api.js
Made the following changes
-added search shopcart by name functionality to search button
> Query button

- .tekton/tasks.yaml
> CD Pipeline Lint

- .tekton/pipeline.yaml
- .tekton/tasks.yaml
> CD Pipeline Test

- .tekton/pipeline.yaml
> CD Pipeline Build

- .tekton/events/event_listener.yaml
- .tekton/events/trigger.yaml
- .tekton/events/trigger_binding.yaml
- .tekton/events/trigger_template.yaml
- .tekton/pipeline.yaml
- k8s/deployment.yaml
- k8s/ingress.yaml
- k8s/service.yaml
- tests/test_routes.py
> CD Pipeline Deploy

- service/__init__.py
> remove authentication

- features/shopcart.feature
- service/static/index.html
- service/static/js/rest_api.js
Now you can add an item to a shopcart
> Add item to shopcart UI
